- .changeset/big-ligers-whisper.md
- .changeset/tasty-pianos-sit.md
- .github/workflows/release-desktop.yml
- README.md
@mvaivre Unfortunately the GitHub action we are using for code-signing and releasing the DW (action-electron-builder) only supports NPM and Yarn. This PR fixes the release workflow using Yarn instead of Bun.
https://github.com/coparse-inc/action-electron-builder/blob/master/index.js#L109
It also fixes some more things related to releasing and updates the docs.
> Fix DW release GH action

- .github/workflows/release-desktop.yml
The problem was that we were using the password of our apple ID as the value of the `APPLE_ID_PASSWORD` and `APPLEIDPASS` vars whereas instead it should have been a password generated specifically for notarization. 
I deleted the `APPLE_ID_PASSWORD` secret from our CI so that we don't get confused again and I created `APPLE_APP_SPECIFIC_PASSWORD` and assigned it to `APPLE_ID_PASSWORD` and `APPLEIDPASS`.
> Fix mac password in CI

- apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
- apps/mobile-wallet/app.config.js
Closes #207
We don't need the HTTPS link anymore since the SDK only redirects to `alephium://`:
- https://github.com/alephium/alephium-web3/blob/master/packages/walletconnect/src/constants.ts#L38
- https://github.com/alephium/alephium-web3/blob/master/packages/walletconnect/src/provider.ts#L466
> Remove Android https deep link

- .changeset/curvy-suits-love.md
- .changeset/green-cheetahs-press.md
- .changeset/tiny-rice-trade.md
- apps/desktop-wallet/src/App.tsx
- apps/desktop-wallet/src/contexts/walletconnect.tsx
- apps/desktop-wallet/src/modals/SendModals/AddressInputs.tsx
- apps/mobile-wallet/src/components/DashboardHeaderActions.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
- apps/mobile-wallet/src/hooks/useInterval.ts
- apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
- packages/shared/lib/walletConnect.ts
This PR attempts to solve the following issues:
- iOS crash due to WalletConnect: https://github.com/alephium/alephium-frontend/issues/213
- If for some reason an exception is thrown while initializing the WC client, we enter an infinite loop. This PR introduces a mechanism for retrying to initialize every 3 seconds instead. Hopefully this was it.
- Fixes https://github.com/alephium/alephium-frontend/issues/215
- Fixes https://github.com/alephium/alephium-frontend/issues/219
- Changes WC project ID, maybe related to https://github.com/alephium/alephium-frontend/issues/221?
- Improves WC client initialization in DW to better understand https://github.com/alephium/alephium-frontend/issues/221
- Shows version number in settings screen: https://github.com/alephium/alephium-frontend/issues/211 …
> Fix MW & DW releases

- .github/workflows/release-desktop.yml
- .github/workflows/test.yml
- apps/desktop-wallet/.signWindows.js
- apps/desktop-wallet/package.json
- pnpm-lock.yaml
Closes https://github.com/alephium/alephium-frontend/issues/265
Closes https://github.com/alephium/alephium-frontend/issues/264
> Sign Windows binary with FIPS 140-2 compliant setup

- .changeset/clean-bikes-thank.md
- apps/mobile-wallet/CHANGELOG.md
- apps/mobile-wallet/android/app/build.gradle
- apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
- apps/mobile-wallet/app.config.js
- apps/mobile-wallet/ios/Alephium/Info.plist
- apps/mobile-wallet/ios/Podfile.lock
- apps/mobile-wallet/package.json
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
- apps/mobile-wallet/src/navigation/BackupMnemonicNavigation.tsx
- apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
- apps/mobile-wallet/src/screens/BackupMnemonic/BackupIntroScreen.tsx
- apps/mobile-wallet/src/screens/new-wallet/ImportWalletSeedScreen.tsx
- pnpm-lock.yaml
Related to #193 
So, it seems that simply having a timer to keep the app active while in the background prevents React Native from going to "sleep" mode, and all WalletConnect requests seem to receive responses! I've tested this on Android simulator and physical device as well as iOS simulator and it works! I look forward to seeing if it also works on an iOS physical device.
> Respond to WalletConnect while app in background

- .github/actions/setup-monorepo/action.yml
- .github/workflows/build-mobile.yml
- apps/mobile-wallet/README.md
- apps/mobile-wallet/app.config.js
- apps/mobile-wallet/eas.json
Closes #190
We can now trigger EAS builds from our CI!
Once this PR is merged, the following options will be available in our GitHub Actions:
- `android`: This triggers an `eas build` and `submit` of a draft internal release. The release can then be later promoted to an open-beta and production through the Google Play Console website. No need to build another one
- `ios-registered-devices`: This triggers an `eas build` for the registered iOS devices. Once the build passes, a URL will be printed in the logs that the registered iOS devices can open to get the new version.
- `ios-testflight`: This is similar to `android` but for iOS: It triggers an `eas build` and `submit`. The TestFlight version can be promoted to a production release through the Apple Store Connect website.
> EAS GitHub workflows

- .changeset/breezy-shrimps-wink.md
- .changeset/clean-windows-sort.md
- apps/desktop-wallet/src/components/AnnouncementBanner.tsx
- apps/desktop-wallet/src/hooks/useLatestGitHubRelease.ts
- apps/desktop-wallet/src/hooks/useThrottledGitHubApi.ts
- apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
- apps/desktop-wallet/src/utils/app-data.ts
- packages/shared/src/store/assets/assetsActions.ts
- packages/shared/src/store/assets/fungibleTokensSlice.ts
- packages/shared/src/types/assets.ts
Here is a quick solution of 2 problems:
1. Infinite loop when GitHub API request fails: If the retry strategy fails, we stop querying until the user re-launches the app
2. Announcement & last version check conflict: We were reusing the same timestamp to throttle these GitHub API requests. The quickest way to solve this that I thought of is to store a serate timestamp for each.
> Fix GitHub API rate issue

- .changeset/orange-beans-lick.md
- apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
- apps/mobile-wallet/app.config.js
- apps/mobile-wallet/eas.json
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
- apps/mobile-wallet/src/persistent-storage/config.ts
- package.json
- patches/react-native-background-actions@3.0.1.patch
- pnpm-lock.yaml
Metamask does the same: https://github.com/MetaMask/metamask-mobile/blob/910313340e43c24473d057825a5a810d32a55a6e/android/app/src/main/AndroidManifest.xml#L28
Same as Rainbow: https://github.com/rainbow-me/rainbow/blob/74d054fa48e7649c7c18376e4da9e78df80d295d/android/app/src/main/AndroidManifest.xml#L25
Possibly related to #352
> Set allowBackup to false & fix crash

- apps/mobile-wallet/src/components/AddressFlatListScreen.tsx
- apps/mobile-wallet/src/components/layout/BottomModal.tsx
- apps/mobile-wallet/src/components/layout/ModalContent.tsx
The trick was to move `inset.bottom` from the container to the content
> [1.0.8] Fix bottom modal padding

- apps/desktop-wallet/announcement.json
Do not merge until 2.2.5 is released otherwise the link in the announcement will be broken.
> Update announcement to point to 2.2.5

- .github/workflows/publish-docker-explorer.yml
The GH workflow for building the explorer image gets stuck, see https://github.com/alephium/alephium-frontend/issues/533.
@killerwhile recommended we remove the `linux/arm/v7` platform. This fixes the workflow: https://github.com/alephium/alephium-frontend/actions/runs/8810828481/job/24183821652
> the docker image for the frontend is probably not needed for linux/arm/v7, we are deploying on mac (arm64) or intel-family (amd64)
cc @polarker
Closes https://github.com/alephium/alephium-frontend/issues/533.
> Delete linux/arm/v7 from explorer dockerfile

- apps/desktop-wallet/posthog-filter-out.json
- apps/desktop-wallet/src/contexts/walletconnect.tsx
- apps/desktop-wallet/src/hooks/useWalletLock.ts
- apps/desktop-wallet/src/modals/AddressSweepModal.tsx
- apps/desktop-wallet/src/modals/SendModals/CallContract/BuildTxModalContent.tsx
- apps/desktop-wallet/src/modals/SendModals/GasSettings.tsx
- apps/desktop-wallet/src/modals/SendModals/SendModal.tsx
- apps/desktop-wallet/src/modals/WalletConnect/SignUnsignedTxModal.tsx
- apps/desktop-wallet/src/storage/addresses/addressesActions.ts
- apps/mobile-wallet/package.json
- apps/mobile-wallet/src/components/WalletSwitchButton.tsx
- apps/mobile-wallet/src/contexts/SendContext.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
- apps/mobile-wallet/src/screens/new-wallet/ImportWalletSeedScreen.tsx
I want to avoid the issue of floading the analytics with errors because of a `useEffect`, like it happened with the GH API rate limits. I went through both our wallets in search of the places we report things to PostHog and removed some. @mvaivre I would like to review them with you and think of a way to ensure that we won't end up with the same problem in the future.
> Remove error analytics

- apps/mobile-wallet/src/features/fund-password/FundPasswordReminderModal.tsx
- apps/mobile-wallet/src/features/fund-password/FundPasswordScreen.tsx
- apps/mobile-wallet/src/hooks/usePassword.ts
- apps/mobile-wallet/src/screens/BackupMnemonic/VerificationSuccessScreen.tsx
- apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
It's weird that when a user sets up a fund password for the first time, the confirmation input field shows an error the moment they type the first character (see video). In my [other PR you mentioned](https://github.com/alephium/alephium-frontend/pull/573#issuecomment-2143854794):
> Also, to make brute forcing less trivial, the password check should be done when tapping on submit, not before:
But there's no point brute forcing your own new password, you are simply trying to set it. I brought back my changes in this case, without affecting the brute force fix of yours.
https://github.com/alephium/alephium-frontend/assets/1579899/44a3dc93-e2bd-4708-b422-b9a9f367c657
Secondly, the fund password should be asked before deleting it, the same way it is asked before editing it (see video). I …
> Fix fund password deletion and verification

- .changeset/beige-frogs-rhyme.md
- apps/explorer/src/api/assets/assetsApi.ts
- apps/explorer/src/components/Amount.tsx
... instead of showing them in the "unknown" tab.
Also patched an issue when decimals are not provided when they should be. 
_Note: typing should be improved in the future following my work on the tanstack branch (more fields can be optional, we should cast less types etc.)_
> Show fungible tokens with broken metadata in the correct tab

- .github/workflows/translations-sync-dw.yml
I found this option in the [cli docs](https://crowdin.github.io/crowdin-cli/commands/crowdin-download-translations) as well as in the [source code of the action](https://github.com/crowdin/github-action/blob/master/action.yml#L75C3-L78). 
We need to do a pass through all our translations and approve them otherwise unapproved translations will be overridden. I went through some of out translations and I found typos and other issues in some. I approved only some. I could use some help here :)
> Export only approved translation strings

- apps/explorer/src/components/AssetLogo.tsx
- apps/explorer/src/components/SearchBar.tsx
- apps/explorer/src/pages/HomePage/HomePage.tsx
This fixes the absence of Alephium logo in AssetLogo.
> Change Alephium logo import style

- .github/workflows/release-desktop.yml
- apps/desktop-wallet/.signWindows.js
- apps/desktop-wallet/locales/en-US/translation.json
- apps/desktop-wallet/package.json
- apps/desktop-wallet/src/modals/AddressSweepModal.tsx
- pnpm-lock.yaml
For a while I want to get rid of the unmaintained `action-electron-builder` action which we had to fork to make it work. In this PR [this whole JS file](https://github.com/nop33/action-electron-builder/blob/master/index.js) is replaced by simple GitHub Action steps.
> Simplify desktop wallet build and release

- .changeset/silver-falcons-guess.md
- apps/mobile-wallet/src/features/auto-lock/useAutoLock.tsx
- apps/mobile-wallet/src/screens/LandingScreen.tsx
- #752
My theory is that the “the app is now active” is never triggered because , for some reason, the appState.current ref is not set to active. I don’t see any reasons why not to initialize the ref with active, just to
be sure. We currently initialize it with AppState.currentState, but I
think it’s safe to assume that the app is active when our code is running for the first time.
> Fix being stuck in empty Landing screen

- .changeset/cold-carpets-kneel.md
- .changeset/khaki-melons-burn.md
- .changeset/silver-falcons-guess.md
- apps/mobile-wallet/CHANGELOG.md
- apps/mobile-wallet/android/app/build.gradle
- apps/mobile-wallet/app.config.js
- apps/mobile-wallet/ios/Alephium/Info.plist
- apps/mobile-wallet/package.json
PR created so that I can build an internal release with the current version number which will later on be promoted to a production release if everything goes well.
> Bump mobile wallet to 1.1.3

- .changeset/moody-peaches-peel.md
- apps/desktop-wallet/CHANGELOG.md
- apps/desktop-wallet/package.json
I've released an RC. I've tested it by setting all addresses to `isDefault: false` and importing a new wallet.
If no-one reports an issue, I'll release in production tomorrow morning (14.08.24).
> Bump desktop wallet to 2.3.7

- apps/desktop-wallet/src/api/addressesListedFungibleTokensDataHooks.ts
- apps/desktop-wallet/src/api/addressesUnlistedTokensHooks.ts
- apps/desktop-wallet/src/api/useAddressesDisplayTokens.ts
- apps/desktop-wallet/src/components/Amount.tsx
- apps/desktop-wallet/src/components/Inputs/SelectOptionToken.tsx
- apps/desktop-wallet/src/features/assetsLists/AssetsBadgesList.tsx
- apps/desktop-wallet/src/features/assetsLists/AssetsTabs.tsx
- apps/desktop-wallet/src/features/assetsLists/NonStandardTokensBalancesList.tsx
- apps/desktop-wallet/src/features/assetsLists/TokenBalancesRow.tsx
- apps/desktop-wallet/src/features/assetsLists/useSortedFungibleTokens.tsx
- apps/desktop-wallet/src/modals/SendModals/AssetAmountsInput.tsx
- apps/desktop-wallet/src/modals/SendModals/CheckAmountsBox.tsx
- apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
- apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/FiltersPanel.tsx
- apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/index.tsx
- apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
- apps/desktop-wallet/src/types/tokens.ts
The main goal of this PR is to delete `makeSelectAddressesTokens` so that components use Tanstack data instead of Redux data.
EDIT:
Audit fails for a package with no patched version, so let's ignore.
```
│ Package             │ micromatch                                             │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <=4.0.7                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ <0.0.0                                                 │
```
> Delete many Redux selectors and use Tanstack data

- apps/mobile-wallet/__tests__/wallet.test.ts
- apps/mobile-wallet/locales/en-US/translation.json
- apps/mobile-wallet/src/App.tsx
- apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
- apps/mobile-wallet/src/persistent-storage/wallet.ts
- apps/mobile-wallet/src/screens/new-wallet/NewWalletSuccessScreen.tsx
- apps/mobile-wallet/src/store/wallet/walletSlice.ts
- apps/mobile-wallet/src/types/wallet.ts
Given the troubles that out internal testing team had today with scanning for active addresses after walelt metadata restore I decided to change the flow and reuse part of the wallet generation flow on metadata restore with some nicer, friendlier messages.
<details><summary>Click to expand screenshot</summary>
</details>
| Step 1 | Step 2 | Step 3 | Step 4
| ----- | ----- | ----- | ----- |
| ![image](https://github.com/user-attachments/assets/583cecb0-1eb2-43b9-80a2-1d5d18608611) | ![image](https://github.com/user-attachments/assets/df6f2bc7-8140-466b-bd64-646aadf753e8) | ![image](https://github.com/user-attachments/assets/1c27b1ae-f034-4375-859c-32b67f568f2c) | ![image](https://github.com/user-attachments/assets/87b3bdb9-797c-4651-afc1-32c076ae2512) |
> Navigate to active address scan screen on metadata restore

- apps/explorer/turbo.json
CI pipeline for deploying Explorer is consistently failing, the reason seems to be that the `build` directory is not generated after running `pnpm ci:build`. 
I am not sure when/where this has become an issue, adding the `outputs` fields in turbo config fixes this.
> Add `outputs` field for Explorer turbo config

- apps/explorer/index.html
So that the explorer can display NFTs from anywhere
> Remove connect-src from CSP

- .changeset/clean-rules-greet.md
- apps/mobile-wallet/src/hooks/useBiometrics.ts
- apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
People still seem to have problems with infinite auth loops: https://github.com/alephium/alephium-frontend/issues/695
This PR shows a tooltip when the auth fails with a message, hoping that it will help us get better feedback.
> Show toast when failing to authenticate

- .changeset/late-squids-smoke.md
- .changeset/selfish-apricots-give.md
- .changeset/thick-coins-breathe.md
- apps/desktop-wallet/locales/en-US/translation.json
- apps/desktop-wallet/package.json
- apps/desktop-wallet/src/components/AddressRow.tsx
- apps/desktop-wallet/src/features/send/CheckAmountsBox.tsx
- apps/desktop-wallet/src/features/send/CheckWorthBox.tsx
- apps/desktop-wallet/src/features/send/sendModals/callContract/CheckTxModalContent.tsx
- apps/desktop-wallet/src/features/send/sendModals/deployContract/CheckTxModalContent.tsx
- apps/desktop-wallet/src/features/send/sendModals/transfer/CheckTxModalContent.tsx
- apps/desktop-wallet/src/modals/SettingsModal/DevToolsSettingsSection.tsx
- pnpm-lock.yaml
In the context of closing #77 which is partially implemented in `next-tanstack` I would like to merge these small changes:
| before | after |
| ----- | ----- |
| <img width="635" alt="image" src="https://github.com/user-attachments/assets/9be27e1e-8de9-4c72-916c-702d240fbd00"> | <img width="636" alt="image" src="https://github.com/user-attachments/assets/05d24b69-1206-48b9-807b-4dcec44a4366"> |
EDIT: I also added this feature that will make our users who asked for it happy:
- #630
- https://github.com/alephium/alephium-frontend/discussions/432
| before | after |
| ----- | ----- |
| <img width="644" alt="image" src="https://github.com/user-attachments/assets/af0e7264-8f3d-40a6-ae43-df7d46daa215"> | <img width="629" alt="image" src="https://github.com/user-attachments/assets/e49bb84f-6594-40 …
> Add clickable NFT name and total worth in Send modal flow

- apps/desktop-wallet/vite.config.ts
https://vite.dev/config/build-options.html#build-assetsinlinelimit
> Prevent small assets from being inlined

- .changeset/clean-spiders-roll.md
- .changeset/moody-crabs-add.md
- apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletNftsSearchStrings.ts
- apps/desktop-wallet/src/components/Inputs/Select.tsx
- apps/desktop-wallet/src/features/send/AddressInputs.tsx
- apps/desktop-wallet/src/features/send/TokensAmountInputs.tsx
- apps/desktop-wallet/src/modals/AddressSelectModal.tsx
This PR implements 2 of the most frequent requests we had from our community:
- Be able to search for an asset in the send modal
- Be able to filter addresses with NFT names
It also optimizes our searchable select modals and reduces rerenders by keeping a local state instead of passing it to the parent component.
Related issues:
- https://github.com/alephium/alephium-frontend/issues/923
- https://github.com/alephium/alephium-frontend/issues/881
- https://github.com/alephium/alephium-frontend/issues/394
> Improve asset selection

- .changeset/afraid-feet-impress.md
- apps/mobile-wallet/src/components/ExpandableRow.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
Closes:
- #762
| before | after |
| ----- | ----- |
| <img width="487" alt="image" src="https://github.com/user-attachments/assets/30c15581-1d22-4740-93f6-01d00845924b"> | <img width="487" alt="image" src="https://github.com/user-attachments/assets/6468ff9f-e94c-4332-ad17-820a5deea958"> |
> Hide bytecode field behind an expandable section

- apps/mobile-wallet/src/components/layout/Screen.tsx
On some devices, `inset.bottom` is 0 so if we want extra padding we have to provide it
> Fix bottom screen padding

- .changeset/large-flowers-eat.md
- apps/mobile-wallet/src/api/addresses.ts
- apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
- apps/mobile-wallet/src/screens/ActivityScreen.tsx
- apps/mobile-wallet/src/store/addressesSlice.ts
- apps/mobile-wallet/src/store/confirmedTransactionsSlice.ts
- apps/mobile-wallet/src/store/pendingTransactionsSlice.ts
- packages/shared/src/constants.ts
Replaces `POST` endpoint with `GET`. This means that "gaps" might be introduced in the Redux transactions slice. To solve the "gaps" issue in the tx list we only allow chunks of `20` items to be displayed in the aggregated tx list, even if we have more on Redux. That way, when the user loads the next page, Redux will be updated with the next page of txs of each address, but the UI will display the next 20 aggregated txs.
> Fix data loading in mobile wallet

- apps/mobile-wallet/locales/en-US/translation.json
- apps/mobile-wallet/src/components/AddressesTokensList.tsx
- apps/mobile-wallet/src/components/BalanceSummary.tsx
- apps/mobile-wallet/src/features/buy/BuyModal.tsx
- apps/mobile-wallet/src/features/buy/buyUtils.ts
- apps/mobile-wallet/src/features/buy/useBanxaUrl.ts
- apps/mobile-wallet/src/features/modals/AppModals.tsx
- apps/mobile-wallet/src/features/receive/screens/QRCodeScreen.tsx
- apps/mobile-wallet/src/screens/Dashboard/DashboardCardButton.tsx
- apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
- apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
This PR:
1. Simplifies BuyModal code
2. Relies on the OS's native browser and opening a tab * **within the app** * (does not create a new task in the task manager - we're still in the app)
3. Fixes rendering issues reported by testers (see below)
4. Fixes Google Pay
5. Adds Buy button in Receive screen and uses selected receive address
6. Adds text below icons in dashboard card buttons
7. Fixes loading glitches
- https://github.com/alephium/alephium-frontend/issues/1089
- https://github.com/alephium/www/pull/181
https://github.com/user-attachments/assets/d4814531-f8c4-402a-bd28-f6a68faf5516
<details><summary>Click to see screenshots</summary>
Tab icons show at the bottom of the webview after switching between apps:
</details>
> Simplify banxa flow using WebBrowser

- apps/mobile-wallet/src/features/buy/BuyModal.tsx
- apps/mobile-wallet/src/features/buy/buyUtils.ts
I replaced the listener with the recommended `useURL` hook
> Remove listener removal

- .changeset/gold-rabbits-nail.md
- apps/desktop-wallet/electron/appProtocol.ts
- apps/desktop-wallet/electron/main.ts
- apps/desktop-wallet/electron/paths.ts
- apps/desktop-wallet/electron/utils.ts
- apps/desktop-wallet/electron/walletConnect.ts
- apps/desktop-wallet/src/features/autoUpdate/AutoUpdateSnackbar.tsx
- apps/desktop-wallet/src/features/autoUpdate/useLatestGitHubRelease.ts
Closes:
- https://github.com/alephium/alephium-frontend/issues/1136
This PR:
1. updates the electron app to serve its local files using the `alephium://` protocol instead of the `file://` protocol, as per [best practice](https://www.electronjs.org/docs/latest/tutorial/security#18-avoid-usage-of-the-file-protocol-and-prefer-usage-of-custom-protocols).
2. Fixes the IPC sender validation rule to properly validate interprocess communication with a production build.
See issue for more details:
- https://github.com/alephium/alephium-frontend/issues/1136
> Fix auto update

- .changeset/calm-hairs-rescue.md
- .changeset/eighty-squids-drive.md
- packages/shared/src/currencies.ts
- packages/shared/src/types/currencies.ts
@tdroxler I get 404 errors from explorer backend for the fiat currency `THB`
```
GET https://backend.mainnet.alephium.org/market/prices/ALPH/charts?currency=thb
POST https://backend.mainnet.alephium.org/market/prices?currency=thb 4
```
Could we please enable it in the next explorer backend release? Thanks!
TODO:
> Add Thai Baht and Hong Kong Dollar

- .changeset/cold-donuts-film.md
- .changeset/hip-eyes-lay.md
- .changeset/ten-papayas-heal.md
- apps/mobile-wallet/ios/Podfile.lock
- apps/mobile-wallet/locales/en-US/translation.json
- apps/mobile-wallet/src/components/buttons/QuickActionButton.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
- apps/mobile-wallet/src/contexts/walletConnect/useWalletConnectToasts.ts
- apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
- apps/mobile-wallet/src/features/buy/BuyModal.tsx
- apps/mobile-wallet/src/features/ecosystem/DAppDetailsModal.tsx
- apps/mobile-wallet/src/features/ecosystem/DAppQuickActionsModal.tsx
- apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
- apps/mobile-wallet/src/features/ecosystem/VisitDAppButton.tsx
- apps/mobile-wallet/tsconfig.json
Closes:
- #1206
- #1203
- https://github.com/alephium/alephium-frontend/issues/1212
- #1162
- https://github.com/alephium/alephium-frontend/issues/1213
> Post eco fixes

- .changeset/grumpy-cycles-pay.md
- apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
- apps/mobile-wallet/app.config.js
- apps/mobile-wallet/ios/Alephium/Info.plist
- apps/mobile-wallet/ios/Podfile.lock
- apps/mobile-wallet/package.json
- apps/mobile-wallet/src/components/NFTImage.tsx
- apps/mobile-wallet/src/components/NFTPlaceholder.tsx
- apps/mobile-wallet/src/components/nft/NftVideo.tsx
- apps/mobile-wallet/src/components/nft/NftVideoPlayIconOverlay.tsx
- apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/NftModal.tsx
- apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/useIsNftCached.ts
- apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/useNftHeaderData.ts
- apps/mobile-wallet/src/features/modals/modalSelectors.ts
- apps/mobile-wallet/src/style/style.d.ts
- apps/mobile-wallet/src/style/themes.ts
- pnpm-lock.yaml
> Video NFTs

- .changeset/fruity-bars-sniff.md
- .changeset/warm-geckos-cheer.md
- apps/desktop-wallet/src/features/transactionsDisplay/ActivityIndicator.tsx
- apps/desktop-wallet/src/pages/unlockedWallet/UnlockedWalletLayout.tsx
- packages/shared-react/src/api/queries/transactionQueries.ts
- packages/shared-react/src/hooks/index.ts
- packages/shared-react/src/hooks/useActivityIndicator.ts
While working on using Tanstack for fetching transaction data in the mobile wallet I had the idea of improving the UX in the desktop wallet, which led to killing 2 🐦 with 1 🪨 :
The problem was that 5 minutes after the user navigates away from the Activity screen the transactions cache data were deleted, because we want to avoid bloating the cache with useless data when addresses are deleted/created (the `queryKey` changes with changes in the list of addresses).
The solution is to keep an active instance of the same query that the Activity page is using, somewhere else. That's when I thought of implementing an Activity Indicator. This way, when addresses are deleted/created, the old cache will be deleted after 5 minutes, but the new cache will be persisted, which leads to the same behavior …
> Fix tx caching and add activity indicator

- apps/mobile-wallet/locales/en-US/translation.json
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
- apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
- apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
- apps/mobile-wallet/src/features/settings/settingsPersistentStorage.ts
- apps/mobile-wallet/src/features/settings/settingsScreen/SettingsScreen.tsx
- apps/mobile-wallet/src/features/settings/settingsSlice.ts
- apps/mobile-wallet/src/screens/Dashboard/CameraScanButton.tsx
- apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
- apps/mobile-wallet/src/types/settings.ts
- Related to #1358
- Implements a polling mechanism to check if the WC sessions get dropped, in which case it shows a message to the user.
- Removes WalletConnect from app settings (what's the point of having it turned off while everyone can access the ecosystem page? On DW we don't allow disabling it)
- Adds "Clear WalletConnect Cache" button in wallet settings (just like the DW)
> Improve WC connection drops UX

- apps/mobile-wallet/locales/en-US/translation.json
- apps/mobile-wallet/src/features/connectTip/ConnectTipModal.tsx
- apps/mobile-wallet/src/features/connectTip/connectTipStorage.ts
- apps/mobile-wallet/src/features/ecosystem/dAppMessaging/DappBrowserContext.tsx
- apps/mobile-wallet/src/features/ecosystem/dAppMessaging/injectedJs.ts
- apps/mobile-wallet/src/features/modals/AppModals.tsx
- apps/mobile-wallet/src/features/modals/modalTypes.ts
I've added a simple "useful tip" modal that shows only once, the first time the wallet receives the `ALPH_IS_PREAUTHORIZED` message from the dApp and the reply is `false`. It will not appear again.
> DApp Connect tip

- apps/mobile-wallet/src/components/animatedBackground/AnimatedBackground.tsx
- apps/mobile-wallet/src/features/qrCodeScan/CameraScanButtonBase.tsx
- apps/mobile-wallet/src/utils/navigation.ts
The scan modal isn't a "proper" modal (not stored in redux), hence the previous bug.
> Fix scan modal opening, dry up useScreenOrModaIsFocused
