alephium/alephium-frontend

.changeset/mean-knives-bake.md
apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
apps/mobile-wallet/src/utils/numbers.ts

Replace comma with full-stop in amount input

---

.changeset/brown-cougars-flash.md
.changeset/honest-seals-explode.md
apps/desktop-wallet/public/electron.js
apps/desktop-wallet/src/components/SnackbarManager.tsx
apps/desktop-wallet/src/pages/HomePage/UnlockPanel.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AmountsOverviewPanel.tsx

Closes #172
Closes #171 
Closes #111
Closes #176

Fix currency, scrollbars, password autofocus, user data path

---

.changeset/famous-garlics-appear.md
.vscode/settings.json
apps/desktop-wallet/public/electron.js
apps/desktop-wallet/src/hooks/useLatestGitHubRelease.ts

Improve desktop wallet auto-updater by considering rc versions

---

.changeset/plenty-pugs-hope.md
apps/explorer/src/components/SearchBar.tsx
apps/explorer/src/utils/strings.ts
apps/explorer/src/utils/util.test.ts

Allow searching by address public key in explorer

---

.changeset/tricky-snails-swim.md
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx

Fix WC double init

---

.changeset/long-steaks-drop.md
apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/src/components/layout/TabBarPager.tsx

This should finally fix this annoying type issue we got when trying to install deps.

Fix type issue with TabBarPager

---

.changeset/cold-geese-bake.md
apps/desktop-wallet/src/components/AssetBadge.tsx

Fix AssetBadge decimals

---

.changeset/afraid-snakes-kneel.md
apps/desktop-wallet/locales/bg-BG/translation.json
apps/desktop-wallet/locales/de-DE/translation.json
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/locales/es-ES/translation.json
apps/desktop-wallet/locales/fr-FR/translation.json
apps/desktop-wallet/locales/id-ID/translation.json
apps/desktop-wallet/locales/it-IT/translation.json
apps/desktop-wallet/locales/pt-PT/translation.json
apps/desktop-wallet/locales/ru-RU/translation.json
apps/desktop-wallet/locales/tr-TR/translation.json
apps/desktop-wallet/locales/vi-VN/translation.json
apps/desktop-wallet/src/contexts/walletconnect.tsx
apps/desktop-wallet/src/modals/SettingsModal/GeneralSettingsSection.tsx
apps/desktop-wallet/src/storage/global/globalActions.ts
apps/desktop-wallet/src/storage/global/snackbarSlice.ts

Related to #240
~~We still need to hook the button with a reset function.~~

Add clear cache button in general settings

---

.changeset/old-baboons-drive.md
.changeset/stupid-eagles-float.md
apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx

Detect biometrics change and fallback to pin

---

.changeset/silver-cherries-film.md
apps/desktop-wallet/src/components/TransactionalInfo.tsx
apps/desktop-wallet/src/types/transactions.ts
apps/desktop-wallet/src/utils/transactions.ts
apps/explorer/src/utils/transactions.ts
apps/mobile-wallet/src/utils/transactions.ts
packages/shared/lib/transactions.ts

Closes https://github.com/alephium/alephium-frontend/issues/288

Fix tx display

---

.changeset/real-masks-invite.md
apps/mobile-wallet/src/components/DashboardHeaderActions.tsx
apps/mobile-wallet/src/components/buttons/ActionButtonsStack.tsx
apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
apps/mobile-wallet/src/screens/ContactListScreenBase.tsx
apps/mobile-wallet/src/screens/Dashboard/WalletConnectPairingsModal.tsx
apps/mobile-wallet/src/screens/LandingScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/AddBiometricsScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/ImportWalletAddressDiscoveryScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/NewWalletIntroScreen.tsx

Add WC QR code scan btn in pairings modal & bug fixes

---

.changeset/hungry-bats-smell.md
apps/desktop-wallet/locales/bg-BG/translation.json
apps/desktop-wallet/locales/de-DE/translation.json
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/locales/es-ES/translation.json
apps/desktop-wallet/locales/fr-FR/translation.json
apps/desktop-wallet/locales/id-ID/translation.json
apps/desktop-wallet/locales/it-IT/translation.json
apps/desktop-wallet/locales/pt-PT/translation.json
apps/desktop-wallet/locales/ru-RU/translation.json
apps/desktop-wallet/locales/tr-TR/translation.json
apps/desktop-wallet/locales/vi-VN/translation.json
apps/desktop-wallet/src/contexts/walletconnect.tsx
apps/desktop-wallet/src/pages/HomePage/UnlockPanel.tsx

Handle WC request when wallet locks

---

apps/desktop-wallet/src/hooks/useThrottledGitHubApi.ts
apps/desktop-wallet/src/utils/app-data.ts

@mvaivre I think this code is more readable, what do you think?

Simplify GitHub api throttle hook

---

.changeset/bright-melons-matter.md
.changeset/tiny-shirts-whisper.md
apps/desktop-wallet/locales/bg-BG/translation.json
apps/desktop-wallet/locales/de-DE/translation.json
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/locales/es-ES/translation.json
apps/desktop-wallet/locales/fr-FR/translation.json
apps/desktop-wallet/locales/id-ID/translation.json
apps/desktop-wallet/locales/it-IT/translation.json
apps/desktop-wallet/locales/pt-PT/translation.json
apps/desktop-wallet/locales/ru-RU/translation.json
apps/desktop-wallet/locales/tr-TR/translation.json
apps/desktop-wallet/locales/vi-VN/translation.json
apps/desktop-wallet/src/components/TransactionalInfo.tsx
apps/desktop-wallet/src/hooks/useTransactionUI.tsx
apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
apps/mobile-wallet/src/components/TransactionListItem.tsx
apps/mobile-wallet/src/hooks/useTransactionUI.ts
apps/mobile-wallet/src/screens/TransactionModal.tsx

Closes #138
Closes #335
Closes #336
This has not been tested, I need to find a testnet wallet that has some failed transactions. If you know of any, please let me know.
This is how it would look like
<details><summary>See screenshots</summary>
</details>

Fix display of failed txs in wallets

---

.changeset/witty-flies-tan.md
apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/src/components/AddressCard.tsx
apps/mobile-wallet/src/components/AuthenticationModal.tsx
apps/mobile-wallet/src/components/BalanceSummary.tsx
apps/mobile-wallet/src/components/ConsolidationModal.tsx
apps/mobile-wallet/src/components/ModalWithBackdrop.tsx
apps/mobile-wallet/src/components/buttons/Button.tsx
apps/mobile-wallet/src/components/buttons/ButtonStack.tsx
apps/mobile-wallet/src/components/buttons/HighlightButton.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
apps/mobile-wallet/src/screens/AddressDiscoveryScreen.tsx
apps/mobile-wallet/src/screens/BackupMnemonic/BackupIntroScreen.tsx
apps/mobile-wallet/src/screens/BackupMnemonic/VerificationSuccessScreen.tsx
apps/mobile-wallet/src/screens/ContactListScreenBase.tsx
apps/mobile-wallet/src/screens/Dashboard/WalletConnectPairingsModal.tsx
apps/mobile-wallet/src/screens/Dashboard/WalletConnectPasteUrlModal.tsx
apps/mobile-wallet/src/screens/DashboardScreen.tsx
apps/mobile-wallet/src/screens/LandingScreen.tsx
apps/mobile-wallet/src/screens/SendReceive/Receive/QRCodeScreen.tsx
apps/mobile-wallet/src/screens/Settings/MnemonicModal.tsx
apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
apps/mobile-wallet/src/screens/Settings/WalletDeleteModal.tsx
apps/mobile-wallet/src/screens/new-wallet/AddBiometricsScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/ImportWalletAddressDiscoveryScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/ImportWalletSeedScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/NewWalletIntroScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/NewWalletSuccessScreen.tsx
apps/mobile-wallet/src/screens/new-wallet/SelectImportMethodScreen.tsx

Closes #92
This PR increases the tappable area around buttons without affecting their position. It has been something that was bothering me when my taps are not registered because I didn't tap right on the button. Google also warned us that we should increase the tappable areas by at least 8px in the smallest of buttons.

Improve accessibility

---

.changeset/big-geese-breathe.md
apps/explorer/src/App.tsx

Works based on my initial testing but needs to be tested with huge addresses.

Reduce fetch-retry number of tries to 3

---

.github/workflows/deploy-mainnet-explorer.yml
.github/workflows/deploy-testnet-explorer.yml

All this does is pinging @killerwhile which is now useless, so he asked me to remove it.

Remove useless workflow

---

.changeset/rare-geese-thank.md
apps/desktop-wallet/src/App.tsx
apps/desktop-wallet/src/storage/transactions/transactionsSelectors.ts
apps/mobile-wallet/src/store/transactions/transactionSelectors.ts
packages/shared/src/transactions.ts

Fix display of NFTs that are in txs but not addresses

---

apps/mobile-wallet/src/store/addressesSlice.ts

Fix initial data loading

---

.changeset/chatty-rivers-reply.md
apps/explorer/locales/en-US/translation.json
apps/explorer/locales/fr-FR/translation.json
apps/explorer/locales/id-ID/translation.json
apps/explorer/src/pages/AddressInfoPage/AssetList.tsx
apps/explorer/src/pages/AddressInfoPage/ExportAddressTXsModal.tsx
apps/explorer/src/pages/AddressInfoPage/NFTDetailsModal.tsx
apps/explorer/src/pages/AddressInfoPage/NFTList.tsx
apps/explorer/src/pages/AddressInfoPage/TokenList.tsx
apps/explorer/src/types/assets.ts
apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj

Fixes #431, https://github.com/alephium/alephium-frontend/issues/424, https://github.com/alephium/alephium-frontend/issues/461

More export options, NFT details fixes, better loading and order by token worth

---

.github/workflows/publish-docker-explorer.yml
apps/explorer/docker/Dockerfile

Tested here https://github.com/alephium/alephium-frontend/actions/runs/8325491173
Fixes #458

Fix explorer docker image build

---

apps/desktop-wallet/src/contexts/walletconnect.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx

Fixes https://github.com/alephium/alephium-frontend/issues/464

Fix WC cache clearing

---

apps/desktop-wallet/src/components/AssetLogo.tsx
apps/mobile-wallet/src/components/AssetLogo.tsx
apps/mobile-wallet/src/components/TokenListItem.tsx

Fix tokens logos un update unverified label

---

apps/desktop-wallet/src/components/ActionLink.tsx
apps/desktop-wallet/src/components/NFTCard.tsx
apps/desktop-wallet/src/components/NFTThumbnail.tsx
apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx

Some simplifications I tried out and committed them directly!

Dw nft modal rtk query ilias

---

apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/package.json
apps/desktop-wallet/src/components/PasswordConfirmation.tsx
apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
apps/desktop-wallet/src/hooks/useWalletLock.ts
apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx
apps/desktop-wallet/src/storage/addresses/addressesStorageUtils.ts
apps/desktop-wallet/src/utils/migration.ts
pnpm-lock.yaml

These changes were already included in the mobile secrets PRs, so I cherry-picked them to fix #543 
Closes #543

Secrets fixes

---

apps/desktop-wallet/src/App.tsx
apps/desktop-wallet/src/components/UpdateWalletBanner.tsx
apps/desktop-wallet/src/contexts/walletconnect.tsx
apps/desktop-wallet/src/features/analytics/AnalyticsProvider.tsx
apps/desktop-wallet/src/modals/SettingsModal/index.tsx
apps/desktop-wallet/src/modals/UpdateWalletModal.tsx

A user reported an issue with the auto update, so I took the opportunity to add more analytics cause we haven't been tracking any and I don't know how to help them

Track more analytics in auto-update system

---

.github/workflows/release-desktop.yml
apps/desktop-wallet/package.json

Related to:
- #586
Inspired by:
- https://github.com/dragonworr/panwriter/commit/73fc8f1b5f9af11a7a2fb397338e6af53fd7521e

Specify electron-builder mac default arch

---

apps/desktop-wallet/src/index.tsx

See https://github.com/PostHog/posthog-js/issues/723

Fix double loading of posthog

---

.changeset/six-hornets-hide.md
apps/desktop-wallet/src/contexts/walletconnect.tsx

Fix WC transfer request

---

.changeset/thin-buckets-vanish.md
.changeset/violet-goats-promise.md
apps/desktop-wallet/src/tests/migration.test.ts
apps/desktop-wallet/src/utils/migration.ts
apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/utils/migration.ts
packages/shared/src/network.ts

Use un-versioned node & explorer endpoints

---

apps/desktop-wallet/locales/id-ID/translation.json

minor translation updates , add 5 strings

Minor Translations updates (Bahasa Indonesia)

---

.github/workflows/translations-sync.yml
crowdin.yml

Add explorer to Crowdin

---

apps/desktop-wallet/src/components/HistoricWorthChart.tsx
apps/desktop-wallet/src/storage/addresses/addressesActions.ts
apps/mobile-wallet/src/store/addressesSlice.ts
apps/mobile-wallet/src/store/loadersSlice.ts

Supersedes https://github.com/alephium/alephium-frontend/pull/680
Closes https://github.com/alephium/alephium-frontend/issues/676
- https://github.com/alephium/alephium-frontend/issues/676

Replaced deprecated history call (rebased)

---

.changeset/grumpy-weeks-repeat.md
apps/mobile-wallet/src/App.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
apps/mobile-wallet/src/store/addressesSlice.ts
apps/mobile-wallet/src/store/appSlice.ts
apps/mobile-wallet/src/store/wallet/walletActions.ts
apps/mobile-wallet/src/store/wallet/walletSlice.ts

Closes #353
This will also be useful when we introduce multiple wallets.
- #353

Improve cold start by preloading data

---

.changeset/stupid-books-share.md
.changeset/sweet-nails-appear.md
.changeset/two-beans-peel.md
apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/package.json
apps/mobile-wallet/src/App.tsx
apps/mobile-wallet/src/components/AssetAmountWithLogo.tsx
apps/mobile-wallet/src/components/NFTImage.tsx
apps/mobile-wallet/src/components/NFTModal.tsx
apps/mobile-wallet/src/components/NFTPlaceholder.tsx
apps/mobile-wallet/src/components/NFTThumbnail.tsx
apps/mobile-wallet/src/components/NFTWebView.tsx
apps/mobile-wallet/src/components/NFTsGrid.tsx
apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
apps/mobile-wallet/src/screens/TransactionModal.tsx
packages/shared/package.json
packages/shared/src/store/assets/assetsActions.ts
pnpm-lock.yaml

This PR addresses these issues:
- https://github.com/alephium/alephium-frontend/issues/658
- https://github.com/alephium/alephium-frontend/issues/28
- https://github.com/alephium/alephium-frontend/issues/425

Improve NFT loading

---

.changeset/moody-peaches-peel.md
.github/workflows/release-desktop.yml
apps/desktop-wallet/package.json
apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
apps/desktop-wallet/src/modals/SettingsModal/DevToolsSettingsSection.tsx
apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
pnpm-lock.yaml

Related to #741
It seems that more people are facing this bug. As a quick solution, I propose that if a default address is not found we return the first one.

Return first address if default not found

---

.changeset/cold-carpets-kneel.md
apps/mobile-wallet/src/components/layout/Screen.tsx
apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/index.tsx

Fix keyboard content overlap

---

apps/explorer/index.html
apps/explorer/public/analytics.js
apps/explorer/src/components/AppFooter.tsx
apps/explorer/tsconfig.json

Integrate GoatCounter in explorer

---

.changeset/wise-jars-add.md
apps/mobile-wallet/src/features/auto-lock/useAutoLock.tsx
apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
apps/mobile-wallet/src/screens/LandingScreen.tsx
patches/react-native-background-actions@3.0.1.patch
pnpm-lock.yaml

Fixes:
- #690
Hopefully also fixes:
- #750 
- #695

Fix stuck in black screen

---

.changeset/little-bobcats-beg.md
apps/mobile-wallet/__tests__/wallet.test.ts
apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/App.tsx
apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
apps/mobile-wallet/src/persistent-storage/contacts.ts
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx

Re-generate wallet metadata if not found

---

apps/desktop-wallet/src/components/AppHeader.tsx
apps/desktop-wallet/src/components/Buttons/ShortcutButtons.tsx
apps/desktop-wallet/src/components/NetworkSwitch.tsx
apps/desktop-wallet/src/components/PageComponents/SideBar.tsx
apps/desktop-wallet/src/features/modals/modalTypes.ts
apps/desktop-wallet/src/modals/AddressDetailsModal.tsx
apps/desktop-wallet/src/modals/AddressOptionsModal.tsx
apps/desktop-wallet/src/modals/AppModals.tsx
apps/desktop-wallet/src/modals/CenteredModal.tsx
apps/desktop-wallet/src/modals/ContactFormModal.tsx
apps/desktop-wallet/src/modals/ModalContainer.tsx
apps/desktop-wallet/src/modals/NewAddressModal.tsx
apps/desktop-wallet/src/modals/NotificationsModal.tsx
apps/desktop-wallet/src/modals/ReceiveModal.tsx
apps/desktop-wallet/src/modals/SecretPhraseModal.tsx
apps/desktop-wallet/src/modals/SettingsModal/EditWalletNameModal.tsx
apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx
apps/desktop-wallet/src/modals/SettingsModal/index.tsx
apps/desktop-wallet/src/modals/SideModal.tsx
apps/desktop-wallet/src/modals/WalletConnectModal.tsx
apps/desktop-wallet/src/modals/WalletQRCodeExportModal.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressesTabContent.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AdvancedOperationsSideModal.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/ContactsTabContent.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/index.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/index.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/UnlockedWalletLayout.tsx
packages/shared-react/src/utils.ts

Continuing the modal refactoring with the following modals:
```
TransactionDetailsModal
AddressOptionsModal
SettingsModal
ReceiveModal
WalletConnectModal
SecretPhraseModal
WalletQRCodeExportModal
EditWalletNameModal
NotificationsModal
AdvancedOperationsSideModal
NewAddressModal
ContactFormModal
```

Modals optimization refactoring (part 2)

---

.changeset/smooth-sloths-grab.md
apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx

Update WC client status if no WC client found

---

.changeset/good-tables-know.md
.changeset/hot-bobcats-yell.md
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/public/electron.js
apps/desktop-wallet/public/preload.js
apps/desktop-wallet/src/api/queryClient.ts
apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
apps/desktop-wallet/src/features/walletConnect/walletConnectContext.tsx
apps/desktop-wallet/src/index.tsx
apps/desktop-wallet/src/pages/HomePage/index.tsx
apps/desktop-wallet/src/storage/dApps/dAppActions.ts
apps/desktop-wallet/src/storage/global/snackbarSlice.ts
apps/desktop-wallet/src/storage/tanstackIndexedDBPersister.ts
apps/desktop-wallet/src/types/window.d.ts

Docs: 
- https://tanstack.com/query/latest/docs/framework/react/plugins/persistQueryClient
Related to:
- #712 
- #126

Persist Tanstack cache

---

apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/src/features/buy/BuyModal.tsx

Update banxa URL

---

.github/workflows/release-desktop.yml

- https://github.com/alephium/alephium-frontend/issues/812

Skip win sign when rc

---

apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/api/apiDataHooks/token/useFetchNft.ts
apps/desktop-wallet/src/components/NFTCard.tsx
apps/desktop-wallet/src/components/NFTThumbnail.tsx
apps/desktop-wallet/src/features/send/TokensAmountInputs.tsx
apps/desktop-wallet/src/modals/NFTDetailsModal.tsx

https://github.com/user-attachments/assets/cb5c4b89-161f-4445-b54d-c755ad6d6525

Improve NFT error display

---

apps/mobile-wallet/app.config.js
apps/mobile-wallet/ios/Alephium/Info.plist

Fix apple warning

---

apps/desktop-wallet/README.md
apps/explorer/README.md
apps/mobile-wallet/README.md

Update release docs

---

.changeset/silver-emus-laugh.md
apps/desktop-wallet/src/features/transactionsDisplay/useTransactionAmountDeltas.ts

Fix amounts of pending txs in tx details modal

---

apps/mobile-wallet/setupErrorHandling.ts

Increase appHangTimeoutInterval to 5s

---

apps/mobile-wallet/setupErrorHandling.ts
apps/mobile-wallet/src/analytics.tsx
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/screens/BackupMnemonic/VerifyMnemonicScreen.tsx
apps/mobile-wallet/src/screens/LandingScreen.tsx
apps/mobile-wallet/src/screens/Settings/MnemonicModal.tsx
apps/mobile-wallet/src/store/addressDiscoverySlice.ts

- https://github.com/alephium/alephium-frontend/issues/972
- https://github.com/alephium/alephium-frontend/issues/968
- https://github.com/alephium/alephium-frontend/issues/927

Fix sentry

---

.changeset/strong-countries-grow.md
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/api/apiDataHooks/apiDataHooksUtils.ts
apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesAlph.ts
apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesTokens.ts
apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletWorth.ts
apps/desktop-wallet/src/components/Amount.tsx
apps/desktop-wallet/src/components/WorthOverview.tsx
apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/WalletWorth.tsx

Data loading indication

---

.changeset/nine-pears-shave.md
apps/desktop-wallet/src/features/send/sendModals/transfer/AddressesTxModalContent.tsx
apps/desktop-wallet/src/modals/AddressSelectModal.tsx

Fix asset selection when default address is empty

---

.changeset/dirty-candles-flash.md
apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressBalances.ts
apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressSingleTokenBalances.ts
apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalances.ts
apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletSingleTokenBalances.ts
apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTokensByType.ts

Fix display of ALPH amounts

---

.changeset/great-gorillas-itch.md
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/components/Buttons/ShortcutButtons.tsx

Disable send btn when wallet empty

---

.changeset/old-owls-behave.md
.changeset/yellow-falcons-search.md
apps/desktop-wallet/src/api/queries/transactionQueries.ts
apps/mobile-wallet/src/api/addresses.ts
apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx
apps/mobile-wallet/src/store/addressesSlice.ts

Use GET txs endpoint instead of POST when only 1 address

---

.changeset/silent-wombats-impress.md
apps/desktop-wallet/src/style/globalStyles.ts
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx

Fixes:
- https://github.com/alephium/alephium-frontend/issues/364

Fix WalletConnect connection removal

---

.changeset/nine-schools-brush.md
apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/components/AddressCard.tsx
apps/mobile-wallet/src/features/address-deletion/AddressCardDeleteButton.tsx
apps/mobile-wallet/src/features/address-deletion/useCanDeleteAddress.tsx
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/store/addresses/addressesActions.ts
apps/mobile-wallet/src/store/addressesSlice.ts

Forget address feature in mobile wallet

---

apps/mobile-wallet/app.config.js

Block media access permissions

---

apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx

Fix iOS freeze

---

apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/components/TopTabBar.tsx
apps/mobile-wallet/src/components/TransactionListItem.tsx
apps/mobile-wallet/src/components/headers/BaseHeader.tsx
apps/mobile-wallet/src/components/layout/TabBarPager.tsx
apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
apps/mobile-wallet/src/navigation/AddressesTabNavigation.tsx
apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
apps/mobile-wallet/src/screens/Addresses/ContactsScreen.tsx
apps/mobile-wallet/src/screens/ContactListScreenBase.tsx

- Implement new addresses/contacts tabs in AddressesScreen
- Fix padding of contacts tab

Mw redesign ilias

---

apps/mobile-wallet/src/components/inputs/Input.tsx
apps/mobile-wallet/src/features/receive/screens/QRCodeScreen.tsx

- Fix destination address paste

Fix destination address paste

---

.changeset/gentle-bottles-argue.md
.changeset/late-owls-reply.md
.changeset/wild-maps-greet.md
apps/desktop-wallet/src/api/queries/transactionQueries.ts
apps/desktop-wallet/src/components/AppHeader.tsx
apps/desktop-wallet/src/components/Inputs/AddressSelect.tsx
apps/desktop-wallet/src/features/refreshData/RefreshButton.tsx
apps/desktop-wallet/src/features/refreshData/useRefreshBalances.ts
apps/desktop-wallet/src/features/send/AddressInputs.tsx
apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
apps/desktop-wallet/src/modals/AddressSweepModal.tsx
apps/desktop-wallet/src/modals/ReceiveModal.tsx

Addresses these issues:
- https://github.com/alephium/alephium-frontend/issues/1035
- https://github.com/alephium/alephium-frontend/issues/981
The workaround I created for addressing [this issue](https://github.com/alephium/alephium-frontend/issues/981#issuecomment-2535493157) is to:
1. Delay data refresh by 2s when new tx hash is detected to give backend some time to refresh it's caches
2. Add refresh button to allow user to do a manual refresh

Fix DW bugs

---

apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/package.json
apps/desktop-wallet/src/components/SnackbarManager.tsx
apps/desktop-wallet/src/features/ledger/ConnectWithLedgerButton.tsx
apps/desktop-wallet/src/features/ledger/LedgerAddressDiscoverySnackbar.tsx
apps/desktop-wallet/src/features/ledger/ledgerActions.ts
apps/desktop-wallet/src/features/ledger/ledgerSlice.ts
apps/desktop-wallet/src/features/ledger/useInitializeAppWithLedgerData.tsx
apps/desktop-wallet/src/features/send/SendModal.tsx
apps/desktop-wallet/src/features/transactionsDisplay/transactionRow/TokenBadgesListCell.tsx
apps/desktop-wallet/src/features/transactionsDisplay/transactionRow/TransactionRow.tsx
apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
apps/desktop-wallet/src/images/ledger.svg
apps/desktop-wallet/src/modals/CenteredModal.tsx
apps/desktop-wallet/src/modals/ModalContainer.tsx
apps/desktop-wallet/src/pages/HomePage/NewWalletActions.tsx
apps/desktop-wallet/src/pages/HomePage/UnlockPanel.tsx
apps/desktop-wallet/src/storage/store.ts

- Remind user to look at the device when signing a transaction
- Welcome user when detecting new Ledger device and ask if they want to do an address discovery

Ledger UX improvements

---

.changeset/cuddly-fishes-leave.md
apps/desktop-wallet/src/features/walletConnect/walletConnectContext.tsx

Refresh dApp connections after failing to disconnect

---

apps/desktop-wallet/src/features/modals/modalTypes.ts
apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
apps/desktop-wallet/src/features/walletConnect/walletConnectContext.tsx
apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
packages/shared-react/package.json
packages/shared-react/src/walletConnect/index.ts
packages/shared-react/src/walletConnect/useWalletConnectNetworkSwitch.ts
packages/shared/src/types/walletConnect.ts
pnpm-lock.yaml

Closes these issues:
- https://github.com/alephium/alephium-frontend/issues/856
- https://github.com/alephium/alephium-frontend/issues/947
Also see: https://github.com/alephium/alephium-frontend/pull/1026#pullrequestreview-2512003381

Fix WalletConnect modals in mobile wallet redesign

---

apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/components/AddressBox.tsx
apps/mobile-wallet/src/components/AddressesTokensList.tsx
apps/mobile-wallet/src/components/headers/BaseHeader.tsx
apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx

Just fixing the lint error in your branch and a small rename for cleaner props:
@mvaivre I've also run the CI to build internal versions for Android and iOS from this branch to proceed with testing.

Redesign polish ilias

---

.changeset/purple-wasps-compete.md
.changeset/red-cows-fly.md
.changeset/strange-candles-crash.md
.changeset/thin-steaks-melt.md
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/features/walletConnect/SignUnsignedTxModal.tsx
apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionRequestEventHandler.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
apps/mobile-wallet/src/types/walletConnect.ts

Closes:
- https://github.com/alephium/alephium-frontend/issues/1083

Support alph_signAndSubmitUnsignedTx

---

.gitignore
apps/desktop-wallet/electron/electron-env.ts
apps/desktop-wallet/electron/main.ts
apps/desktop-wallet/electron/preload.ts
apps/desktop-wallet/package.json
apps/desktop-wallet/src/components/AppHeader.tsx
apps/desktop-wallet/src/components/TitleBar.tsx
apps/desktop-wallet/src/index.css
apps/desktop-wallet/src/style/globalStyles.ts
apps/desktop-wallet/src/utils/platform.ts
pnpm-lock.yaml

- Added title bar
- Added ipc handlers to minimize, maximize, close desktop wallet
- Bumped electron dev tools to v4 since there were build issues on Windows
- Added exception handling when installing devtools

feat: Add title bar for frameless desktop-wallet

---

apps/mobile-wallet/package.json
apps/mobile-wallet/src/navigation/InWalletNavigation.tsx
apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
pnpm-lock.yaml

Closes:
- #598
It's not used anymore

Remove `react-native-portalize`

---

apps/mobile-wallet/CHANGELOG.md
apps/mobile-wallet/src/App.tsx
apps/mobile-wallet/src/store/addressesSlice.ts

Tanstack will deprecate all this.

Fix prices on mobile wallet

---

apps/mobile-wallet/src/components/AddressesTokensList.tsx
apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx

Fixed padding + try a new design (using border only to better show it's an "empty space" vs. an active surface).

Fix empty placeholders

---

apps/mobile-wallet/src/components/AnimatedBackground.tsx
apps/mobile-wallet/src/screens/LandingScreen.tsx

Default AnimatedBackground width to screenwidth

---

.changeset/warm-jokes-live.md
apps/desktop-wallet/package.json
apps/desktop-wallet/src/api/apiDataHooks/utils/useMergeAllTokensBalances.ts
apps/desktop-wallet/src/components/Inputs/SelectOptionAddress.tsx
apps/desktop-wallet/src/components/Inputs/SelectOptionItemContent.tsx
apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
apps/desktop-wallet/src/features/walletConnect/useSignerAddress.ts

Closes:
- #1129
- https://github.com/alephium/alephium-frontend/issues/1131
- https://github.com/alephium/alephium-frontend/issues/1128

Pre 2.5.1 release fixes

---

apps/mobile-wallet/src/components/AddressesTokensList.tsx
apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
apps/mobile-wallet/src/features/modals/BottomModal.tsx
apps/mobile-wallet/src/features/modals/useBottomModalState.tsx

Perfs boost in AddressDetails modal

Lookout for bottom modal animation, wait before loading heavy content

---

.changeset/eleven-jokes-smile.md
apps/mobile-wallet/src/features/modals/BottomModalBase.tsx

Close modals on back press

---

.changeset/three-files-cross.md
apps/desktop-wallet/src/features/analytics/useTrackUserSettings.ts
apps/desktop-wallet/src/features/send/SendModal.tsx
apps/desktop-wallet/src/features/send/StepsProgress.tsx
apps/desktop-wallet/src/features/send/sendModals/callContract/CheckTxModalContent.tsx
apps/desktop-wallet/src/features/send/sendModals/deployContract/CheckTxModalContent.tsx
apps/desktop-wallet/src/features/send/sendModals/transfer/CheckTxModalContent.tsx
apps/desktop-wallet/src/features/settings/settingsSelectors.ts
apps/desktop-wallet/src/modals/SettingsModal/GeneralSettingsSection.tsx

Password should not be needed when a wallet is using Ledger.
@nop33 I don't have my ledger wallet with me so I can't test properly.
Note: I took this opportunity to optimise some Redux selectors.

Fix password requirement for Ledger wallets

---

apps/mobile-wallet/CHANGELOG.md
apps/mobile-wallet/src/components/AddressBox.tsx
apps/mobile-wallet/src/components/AppText.tsx
apps/mobile-wallet/src/components/AssetAmountWithLogo.tsx
apps/mobile-wallet/src/components/BalanceSummary.tsx
apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModalBalanceSummary.tsx

Scale balance font-size to fit

---

.changeset/four-queens-rest.md
apps/mobile-wallet/src/contexts/SendContext.tsx
apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModalHeader.tsx
apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/NftModal.tsx
apps/mobile-wallet/src/features/send/SendButton.tsx
apps/mobile-wallet/src/features/send/screens/AssetsScreen/index.tsx
apps/mobile-wallet/src/features/send/screens/DestinationScreen.tsx
apps/mobile-wallet/src/navigation/SendNavigation.tsx
apps/mobile-wallet/src/navigation/rootStackRoutes.ts

Add send button in NFT details modal

---

.changeset/swift-turtles-play.md
apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
apps/mobile-wallet/src/features/ecosystem/DAppsList.tsx
apps/mobile-wallet/src/features/ecosystem/DAppsTags.tsx
apps/mobile-wallet/src/features/ecosystem/EcosystemScreen.tsx

The feature is still hidden and it won't be enabled in this PR.

Add navigation buttons in ecosystem dApp WebView

---

apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/components/AddressesTokensList.tsx
apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
apps/mobile-wallet/src/components/NFTsGrid.tsx
apps/mobile-wallet/src/components/TokenListItem.tsx
apps/mobile-wallet/src/components/buttons/QuickActionButton.tsx
apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
apps/mobile-wallet/src/features/addressesManagement/AddressQuickActionsModal.tsx
apps/mobile-wallet/src/features/assetsDisplay/hideAssets/HiddenAssetsScreen.tsx
apps/mobile-wallet/src/features/assetsDisplay/hideAssets/SelectAssetToHideModal.tsx
apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/TokenQuickActionsModal.tsx
apps/mobile-wallet/src/features/ecosystem/DAppsList.tsx
apps/mobile-wallet/src/features/ecosystem/EcosystemScreen.tsx
apps/mobile-wallet/src/features/send/screens/AssetsScreen/AssetRow.tsx
apps/mobile-wallet/src/modals/AddressPickerQuickActionsModal.tsx
apps/mobile-wallet/src/navigation/AddressesTabNavigation.tsx
apps/mobile-wallet/src/navigation/InWalletNavigation.tsx
apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
apps/mobile-wallet/src/screens/Addresses/Contact/ContactScreen.tsx
apps/mobile-wallet/src/screens/ContactListScreenBase.tsx
apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
apps/mobile-wallet/src/style/themes.ts

And now I really go back to DW :P

Tweaks and fixes

---

apps/mobile-wallet/ios/Podfile.lock

@mvaivre I keep getting this diff cause I can't run `pnpm ios` without first running `pnpm dlx pod-install`. Can you please check this branch to your local machine and see if you get any problems when running `pnpm ios`?

Pod install

---

apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/components/SearchInput.tsx
apps/mobile-wallet/src/features/ecosystem/DAppCard.tsx
apps/mobile-wallet/src/features/ecosystem/DAppsList.tsx
apps/mobile-wallet/src/features/ecosystem/DAppsTags.tsx
apps/mobile-wallet/src/features/ecosystem/EcosystemScreen.tsx
apps/mobile-wallet/src/screens/ContactListScreenBase.tsx

Add search bar in ecosystem screen

---

.changeset/ten-steaks-appear.md
apps/mobile-wallet/src/components/AddressBox.tsx
apps/mobile-wallet/src/components/ExpandableRow.tsx
apps/mobile-wallet/src/components/inputs/ColorPicker.tsx
apps/mobile-wallet/src/features/addressesManagement/AddressSettingsModal.tsx
apps/mobile-wallet/src/screens/Addresses/Address/AddressForm.tsx
apps/mobile-wallet/src/screens/Addresses/Address/NewAddressScreen.tsx

- Fixes misaligned address box colored badge and address label
- https://github.com/alephium/alephium-frontend/issues/1183

Alignments & Keyboard

---

packages/shared/src/store/assets/fungibleTokensSlice.ts

Fix ALPH logo

---

.changeset/silly-books-rule.md
apps/mobile-wallet/src/features/modals/modalActions.ts
apps/mobile-wallet/src/features/modals/modalSlice.ts
apps/mobile-wallet/src/features/send/SendButton.tsx

Close all modals before send navigation

---

apps/mobile-wallet/src/components/inputs/Input.tsx
apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx

Check for clipboard content before getting text

---

apps/mobile-wallet/src/components/BiometricsWarningModal.tsx
apps/mobile-wallet/src/components/RadioButtonRow.tsx
apps/mobile-wallet/src/components/SearchInput.tsx
apps/mobile-wallet/src/components/buttons/Button.tsx
apps/mobile-wallet/src/components/inputs/Input.tsx
apps/mobile-wallet/src/features/modals/BottomModal.tsx
apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
apps/mobile-wallet/src/features/modals/BottomModalFlashList.tsx
apps/mobile-wallet/src/features/modals/BottomModalHeader.tsx

Some little tweaks to input and radio buttons

Searchable flashlists mika

---

apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx

Use flashlist for addresses list in addresses screen

---

.changeset/warm-schools-jog.md
apps/mobile-wallet/src/components/Amount.tsx
apps/mobile-wallet/src/features/send/modals/TokenAmountModal.tsx

Very useful when someone wants to send a certain amount of fiat-equivalent to someone else.
See feature request: 
- https://github.com/alephium/alephium-frontend/discussions/432

Display entered amount fiat worth

---

apps/mobile-wallet/src/components/NFTImage.tsx

Add bg to NFT thumbnails

---

.changeset/tall-frogs-tickle.md
apps/mobile-wallet/src/components/SecretPhraseWordList.tsx
apps/mobile-wallet/src/features/backup/backupScreens/VerifyMnemonicScreen.tsx

Hide already entered words of imported mnemonic

---

apps/desktop-wallet/package.json
apps/desktop-wallet/src/features/send/SendModal.tsx
apps/desktop-wallet/src/features/send/sendModals/transfer/TransferSendModal.tsx
apps/desktop-wallet/src/features/send/sendTypes.ts

Fix consolidation

---

apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/components/InfoBox.tsx
apps/desktop-wallet/src/features/ledger/ConnectLedgerInstructionsPage.tsx
apps/desktop-wallet/src/features/settings/settingsConstants.ts
apps/desktop-wallet/src/hooks/useAddresses.ts
apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/AddressSortingSelect.tsx

Closes:
- #1120
| Before | After |
| ----- | ------|
| <img width="1012" alt="image" src="https://github.com/user-attachments/assets/99d8ee04-f357-4fad-8675-9339cacc951e" /> | <img width="1012" alt="image" src="https://github.com/user-attachments/assets/51b1848e-82bd-4a9a-a910-982453019df5" /> |

Sort addresses by index & improve Ledger instructions page

---

apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressFtsSorted.ts
apps/desktop-wallet/src/api/transactions.ts
apps/desktop-wallet/src/features/send/SendModal.tsx
apps/desktop-wallet/src/features/send/sendModals/callContract/CallContractSendModal.tsx
apps/desktop-wallet/src/features/send/sendModals/deployContract/DeployContractSendModal.tsx
apps/desktop-wallet/src/features/send/sendModals/transfer/TransferSendModal.tsx
apps/desktop-wallet/src/features/walletConnect/useSignerAddress.ts
apps/desktop-wallet/src/modals/AddressSweepModal.tsx
apps/desktop-wallet/src/modals/SettingsModal/DevToolsSettingsSection.tsx
apps/mobile-wallet/src/api/transactions.ts
apps/mobile-wallet/src/contexts/SendContext.tsx
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/store/addressesSlice.ts
apps/mobile-wallet/src/types/wallet.ts
packages/keyring/src/keyring.ts
packages/shared/src/types/addresses.ts

Store pubKey in Redux to fix Ledger unlocks

---

apps/mobile-wallet/android/gradle.properties
apps/mobile-wallet/app.config.js
apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/ios/Podfile.properties.json
apps/mobile-wallet/src/components/layout/ScrollScreen.tsx

Tanstack & Expo [7/8]: Enable new architecture

---

apps/mobile-wallet/__tests__/wallet.test.ts
apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/package.json
apps/mobile-wallet/src/App.tsx
apps/mobile-wallet/src/features/assetsDisplay/hideTokens/hiddenTokensStorage.ts
apps/mobile-wallet/src/features/ecosystem/favoriteDAppsStorage.ts
apps/mobile-wallet/src/features/settings/settingsScreen/SettingsDevSection.tsx
apps/mobile-wallet/src/features/settings/useLoadStoredSettings.ts
apps/mobile-wallet/src/persistent-storage/app.ts
apps/mobile-wallet/src/persistent-storage/storage.ts
apps/mobile-wallet/src/persistent-storage/tanstackAsyncStoragePersister.ts
apps/mobile-wallet/src/persistent-storage/utils.ts
apps/mobile-wallet/src/persistent-storage/wallet.ts
apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
pnpm-lock.yaml

Tanstack & Expo [8/8]: Replace AsyncStorage with MMKV

---

.changeset/real-showers-sin.md
apps/explorer/src/components/AppFooter.tsx
apps/explorer/src/components/AppHeader.tsx
apps/explorer/src/components/Cards/Card.tsx
apps/explorer/src/components/Charts/LineAreaChart.tsx
apps/explorer/src/components/Menu.tsx
apps/explorer/src/components/NetworkLogo.tsx
apps/explorer/src/components/SectionTitle.tsx
apps/explorer/src/components/Select.tsx
apps/explorer/src/components/Table/Table.tsx
apps/explorer/src/components/Table/TableRow.tsx
apps/explorer/src/components/ThemeSwitcher.tsx
apps/explorer/src/pages/AddressInfoPage/AddressTransactionRow.tsx
apps/explorer/src/pages/BlockInfoPage.tsx
apps/explorer/src/styles/themes.ts

+ misc UI improvements
To be merged after #1337

Compactify layout 

---

apps/mobile-wallet/ios/Podfile.lock
apps/mobile-wallet/package.json
apps/mobile-wallet/src/components/Amount.tsx
apps/mobile-wallet/src/components/buttons/ActionCardButton.tsx
apps/mobile-wallet/src/components/buttons/Button.tsx
apps/mobile-wallet/src/components/headers/BaseHeader.tsx
apps/mobile-wallet/src/contexts/HeaderContext.tsx
apps/mobile-wallet/src/features/modals/BottomModal2.tsx
apps/mobile-wallet/src/features/modals/BottomModalBackdrop.tsx
apps/mobile-wallet/src/hooks/layout/useScreenScrollHandler.tsx
apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
apps/mobile-wallet/src/style/themes.ts
pnpm-lock.yaml

Mobile fixes

---

apps/explorer/src/pages/AddressInfoPage/index.tsx

FYI @nop33, missing return statement that I added in the AddressInfoPage component, but forgot to add after I implemented your solution. I'm going ahead and merging & deploying this.

Add missing return to avoid blank screen

---

apps/explorer/src/pages/AddressInfoPage/AddressTransactionRow.tsx

Fix explorer tx display

---

apps/desktop-wallet/src/components/TokenAmountsBox.tsx
apps/desktop-wallet/src/features/send/sendModal/SendModalInfoCheckStep.tsx
apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTAmounts.tsx
apps/desktop-wallet/src/features/walletConnect/SignDeployContractTxModal.tsx
apps/desktop-wallet/src/features/walletConnect/SignExecuteScriptTxModal.tsx
apps/desktop-wallet/src/features/walletConnect/SignTransferTxModal.tsx

Fix transactionDetailsModal's TokenAmountsBox amounts

---

apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
apps/desktop-wallet/src/hooks/useWalletLock.ts
apps/desktop-wallet/src/modals/NewAddressModal.tsx
apps/desktop-wallet/src/tests/api/retry.test.tsx

- Closes https://github.com/alephium/alephium-frontend/issues/1440
- Closes https://github.com/alephium/alephium-frontend/issues/1441
- Closes https://github.com/alephium/alephium-frontend/issues/1443

Groupless fixes

---

apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/components/Amount.tsx

Fixes https://github.com/alephium/alephium-frontend/issues/1427 https://github.com/alephium/alephium-frontend/issues/971

DW discreet mode fix

---

apps/mobile-wallet/src/components/ModalWithBackdrop.tsx
apps/mobile-wallet/src/components/QRCodeScannerModal.tsx

- Closes #1439
This helped:
- https://github.com/facebook/react-native/issues/50442#issuecomment-2821086876

Fix QR code scanner

---

.changeset/fluffy-ends-shine.md
.changeset/full-cycles-slide.md
apps/desktop-wallet/package.json
apps/explorer/package.json
apps/mobile-wallet/package.json
packages/shared-react/package.json
packages/shared-react/src/api/queries/tokenQueries.ts
packages/shared/package.json
pnpm-lock.yaml

Fix tokens list

---

apps/mobile-wallet/src/components/footers/FooterMenu.tsx
apps/mobile-wallet/src/components/footers/FooterMenuItem.tsx

Increase FooterMenuItems hit rect

---

.changeset/old-books-smash.md
apps/mobile-wallet/locales/en-US/translation.json
apps/mobile-wallet/src/components/AddressBox.tsx
apps/mobile-wallet/src/screens/Addresses/Address/NewAddressScreen.tsx
packages/shared/src/types/addresses.ts

Indicate newly created address with "New" badge

---

.changeset/chilly-friends-boil.md
apps/mobile-wallet/src/features/ecosystem/EditDappUrlModal.tsx
apps/mobile-wallet/src/features/fund-password/FundPasswordModal.tsx
apps/mobile-wallet/src/features/settings/EditWalletNameModal.tsx
apps/mobile-wallet/src/features/settings/WalletDeleteModal.tsx
apps/mobile-wallet/src/features/walletconnect/WalletConnectPasteUrlModal.tsx

- Closes #1495
- See: https://github.com/gorhom/react-native-bottom-sheet/issues/2146#issuecomment-3254979680

Fix text input lag

---

.changeset/good-chicken-speak.md
.changeset/loose-paws-beg.md
apps/desktop-wallet/locales/en-US/translation.json
apps/desktop-wallet/src/features/walletConnect/SignUnsignedTxModal.tsx
apps/mobile-wallet/src/features/ecosystem/modals/SignUnsignedTxModal.tsx
packages/shared-react/src/api/queries/transactionQueries.ts
packages/shared/src/types/signTxModalTypes.ts

Fix signing when decoding fails
